---
- name: Simple Test (No Sudo)
  hosts: all
  gather_facts: yes
  become: no
  
  tasks:
    - name: Print message
      debug:
        msg: "Ansible is working!"
    
    - name: Check hostname
      command: hostname
      register: hostname_result
    
    - name: Show hostname
      debug:
        msg: "Hostname: {{ hostname_result.stdout }}"
    
    - name: Check current directory
      command: pwd
      register: pwd_result
    
    - name: Show directory
      debug:
        msg: "Directory: {{ pwd_result.stdout }}"
