---
app_name: petclinic
app_image: petclinic-local:latest
app_host_port: 8080
app_container_port: 8080
app_ports:
  - "{{ app_host_port }}:{{ app_container_port }}"
app_env:
  JAVA_OPTS: "-Xmx512m -Xms256m"
